sudo: false

language: python

python:
  - 3.5

env:
  - TOX_ENV="py35"
  - TOX_ENV="pep8"
  - TOX_ENV="docs"

install:
  - pip install tox==2.5.0
  - pip install codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
