sudo: false

language: python

python:
  - 3.5

env:
  - TOX="py35"
  - TOX="pep8"
  - TOX="docs"

install:
  - pip install tox==2.5.0
  - pip install codecov

script:
  - tox

after_success:
  - codecov
